source = $HOME/.config/hypr/colors.conf
source = $HOME/.config/hypr/settings.conf

# GENERAL
general {
  disable_loading_bar = true
  hide_cursor = false
}

# BACKGROUND
background {
  monitor = 
  path = $HOME/.config/hypr/wallpapers/wallpaper.png
  blur_passes = 2 
  color = $base
}

# TIME
label {
  monitor =
  text = cmd[update: 60000] date '+%I:%M%p on %A %m/%d/%y'
  color = $text
  font_size = 15
  font_family = $font
  position = -10, 5
  halign = right
  valign = bottom
}

# USER AVATAR
image {
  monitor =
  path = $HOME/.face
  size = 200
  position = 0, 150
  halign = center
  valign = center
  border_size = 0
}

label {
    monitor = 
    text = $user_first_last
    font_family = $font
    color = $text
    font_size = 20
}

# INPUT FIELD
input-field {
  monitor =
  size = 300, 45
  border_color = $accent
  outline_thickness = 0
  rounding = 10
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = false
  outer_color = $accent
  inner_color = $base
  font_color = $text
  fade_on_empty = false
  placeholder_text = 󰌾  Password 
  hide_input = false
  check_color = $accent
  fail_color = $red
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  position = 0, -80
  halign = center
  valign = center
}

# Current Music
label {
    color = $text_dim
    text = cmd[update: 1000] sh -c $HOME/.config/hypr/scripts/status_text.py
    font_size = 12
    halign = center
    valign = bottom
    position = 0, 20
}
